---
title: "Tips for working on the AHPCC with R"
format: pdf
editor: visual
---

## The AHPCC & R

The Arkansas High Performance Computing (AHPCC) offers excellent computing resources free of charge for students and faculty at institutions of higher education in Arkansas! However running analyses in R (especially those that require a lot of spatial package dependencies like `gdal`) can be a challenge. Here are a few tips to help, beyond what can be found on the AHPCC wiki (<https://hpcwiki.uark.edu/doku.php>).

## Conda

The easiest way I have found to use R on the AHPCC is through a `conda` environment. After connecting to the login node:

```{bash}
ssh user@hpc-portal2.hpc.uark.edu
```

you can request resources to start an interactive job (e.g. 1 hr on the comp01 partition with 10 cpus):

```{bash}
srun --nodes=1 --ntasks-per-node=1  --cpus-per-task=10 --partition comp01 --time=1:00:00 --pty /bin/bash 
```

It is a good idea to start a virtual terminal (e.g. with `screen`) BEFORE requesting an interactive job.

After being sent to a worker node to start your job, you will then need to run the following to be able to access `conda`:

```{bash}
source /share/apps/bin/conda-3.10.sh
```

Other versions of conda can also be accessed.

For jobs not run interactively (submitted to the queue), be sure to also include the `source /share/apps/bin/conda-3.10.sh` line as part of your job submission script.

After creating a new conda environment, you can install non-R dependencies as usual (e.g. `conda install gdal`) whereas R packages normally have a `r-` prefix (e.g. `conda install r-rgdal`).

## ENM

To run ENMs using MaxEnt algorithm, I typically use the `enmeval` package. Make sure devtools is installed into your conda environment (`conda install r-devtools)` and then start your R session. Within R, ENMeval can be installed using `devtools::install_github("jamiemkass/ENMeval")`.
